# Generated by cucumber-sinatra. (2017-04-06 08:23:50 -0700)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'site/app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = MicroAuthority

class MicroAuthorityWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  MicroAuthorityWorld.new
end
